---
- name: Copy interfaces configuration
  become: true
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: 
    - reload interfaces
    - reload frr.service
  tags:
    - interfaces
