---
- name: install default packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ default_packages }}"

- name: install if_throughput.sh script
  become: true
  copy:
    src: if_throughput.sh
    dest: /usr/local/bin/if_throughput.sh
    mode: a+x
