- name: start frr.service
  become: true
  service:
    name: frr
    enabled: yes
    state: started

- name: reload frr.service
  become: true
  service:
    name: frr
    state: reloaded

- name: restart frr.service
  become: true
  service:
    name: frr
    enabled: yes
    state: restarted

- name: restart ntp.service
  become: true
  service:
    name: ntp
    state: restarted

- name: reload interfaces
  become: true
  command: "ifreload -a"

- name: restart switchd.service
  become: true
  service:
    name: switchd
    state: restarted

- name: restart snmpd.service
  become: true
  service:
    name: snmpd
    state: restarted


############################
# DHCP relay service per VRF
############################
# https://docs.cumulusnetworks.com/display/CL35/Virtual+Routing+and+Forwarding+-+VRF
# Cumulus Linux does not support DHCP server and relay across VRFs, so the server and host cannot be in different VRF tables. In addition, the server and relay cannot be in different VRF tables.

# Example:

- name: restart dhcrelay.service
  become: true
  service:
    name: dhcrelay@{{ item.name | lower }}
    enabled: yes
    state: restarted
  with_items: "{{ configured_vrfs }}"
