---
# DNS #
#######

nameservers:
  - 1.1.1.1
  - 1.0.0.1

resolv_domain: "example.local"
resolv_search: "example.local"

# NTP #
#######

ntpservers:
  - ntp01.example.local
  - ntp02.example.local

ntp_listen_interface: "eth0"
default_timezone: "Europe/Zurich"
