---
# These are common settings which define the baseline configuration of a CumulusLinux Device #
##############################################################################################

ansible_user: cumulus # defines what user is used by ansible

# define names for the different security blocks (needs to be the same as assigned to the switches in netbox)
securityblock1: INT
securityblock2: DMZ

# eth0 on each switch is reserved for out of band management. Set geteway to avoid asymmetric routing for management traffic.
# define the gateway for every oob management network. The variables are used in interfaces.j2 template.
oob_gateway_sb1: 192.168.70.1
oob_gateway_sb2: 192.168.71.1 

# repo and vagrant interface ips are used in interfaces.j2 template to route traffic to repo through vagrant interface #
########################################################################################################################

repo_ip: 172.16.70.1
vagrant_gw: 192.168.121.1

# which additional Debian packages to install on Cumulus switches #
###################################################################

install_packages: true

default_packages:
  - vim

install_etckeeper: true

# apt repos #
#############

# uncomment for definition of sources if you host your own repo and make sure
# the file is in the "files" folder in the cumulus role
#cumulus_repo_file: sources.list

# configure snmp on cumulus devices #
#####################################

snmp_ro_community: public
snmp_allowed_hosts: "10.0.0.0/8"

# define bond slaves for peerlink #
###################################

# definition of ports used for peerlinks on each switch. explanation of peer link: https://docs.cumulusnetworks.com/display/CL36/Multi-Chassis+Link+Aggregation+-+MLAG
peerlink_bond_slaves: ['swp49', 'swp50'] 
